### Create a new user
POST http://localhost:8080/user
Content-Type: application/json

{
    "name": "John Doe",
    "gender": "male",
    "age": 30
}

### Get the user by ID
GET http://localhost:8080/user/{1}
Content-Type: application/json

### Delete the user by ID
DELETE http://localhost:8080/user/{2}
Content-Type: application/json
